"# Carpeta raíz de salida": null
output_path: "./emails_out"

"# Idioma esperado y etiqueta de país": null
language:
  code: "es"        # ISO-639-1 para validación automática (langdetect)
  region_tag: "ES_MX"  # sufijo en nombre de archivo

"# Ventana temporal máxima": null
max_age_days: 365

"# Límite duro de correos por cuenta (0 = sin límite)": null
max_emails_per_account: 0

"# Parámetros de lectura": null
fetch:
  chunk_size: 200  # tamaño de lote de UIDs por lectura para robustez

"# Control de carpetas origen (por proveedor)": null
folders:
  gmail:
    include: ["INBOX", "[Gmail]/Spam"]     # puedes quitar Spam si prefieres curar más
  hotmail:
  include: ["INBOX", "Junk Email", "Spam"]

# Reglas de clasificación (enriquecidas)
rules:
  spam_keywords:
    - "viagra"
    - "cialis"
    - "levitra"
    - "sexo"
    - "porn"
    - "casino"
    - "apuesta"
    - "ruleta"
    - "tragamonedas"
    - "lotería"
    - "rifa"
    - "promoción"
    - "oferta exclusiva"
    - "descuento"
    - "rebaja"
    - "gratis"
    - "free"
    - "2x1"
    - "liquidación"
    - "promo"
    - "suscríbete"
    - "haz clic aquí"
    - "click aquí"
    - "haz click aquí"
    - "unsubscribe"
    - "dar de baja"
    - "bono"
    - "regalo"
    - "premio"
    - "vale"
    - "tarjeta regalo"
    - "cupon"
    - "cupón"
    - "oferta limitada"
    - "última oportunidad"
    - "urgente"
    - "no lo dejes pasar"
    - "didi"
    - "mural.com.mx"

  scam_keywords:
    - "transfer"
    - "wire transfer"
    - "bitcoin"
    - "ethereum"
    - "criptomoneda"
    - "crypto"
    - "herencia"
    - "heredero"
    - "millones"
    - "ganador"
    - "ganaste"
    - "dinero fácil"
    - "dinero rápido"
    - "dinero"
    - "préstamo inmediato"
    - "urgent"
    - "urgente"
    - "reclama ahora"
    - "verifica tu cuenta"
    - "restablece tu contraseña"
    - "account locked"
    - "bloqueada"
    - "inicia sesión"
    - "clave otp"
    - "token"
    - "código de verificación"
    - "actualiza tus datos"
    - "confirmar identidad"
    - "seguridad bancaria"
    - "ganar desde casa"
    - "trabajo fácil"
    - "multinivel"
    - "network marketing"
    - "hazte rico"
    - "retira tu dinero"

  suspicious_headers:
    - "spf=fail"
    - "dkim=fail"
    - "dmarc=fail"
    - "Received-SPF: neutral"
    - "Received-SPF: softfail"
    - "authentication-results: fail"
    - "from unknown"
    - "from untrusted"

  # Dominios de marketing legítimos (permitidos para Clean si no disparan otras reglas)
  credible_marketing_domains:
    - "amazon.com"
    - "mercadolibre.com"
    - "mercadopago.com"
    - "microsoft.com"
    - "google.com"
    - "netflix.com"
    - "spotify.com"
    - "adobe.com"

  # Dominios que frecuentemente envían spam/promociones dudosas (eleva a Suspicious si coincide)
  frequent_spam_domains:
    - "info.news"
    - "mailer.online"
    - "clickmail.cc"
    - "mail-track.io"

  # Términos específicos de juegos de azar (refuerza Spam)
  gambling_terms:
    - "apuesta"
    - "apuestas"
    - "casino"
    - "ruleta"
    - "tragamonedas"
    - "lotería"
    - "loteria"
    - "blackjack"

  # Acortadores de URL comunes (pueden indicar ocultamiento -> Suspicious si junto a otros, Spam si solo)
  url_shorteners:
    - "bit.ly"
    - "tinyurl.com"
    - "t.co"
    - "ow.ly"
    - "is.gd"

  # Patrones de evasión (caracteres repetidos, unicode engañoso, prefijos alfanuméricos largos)
  evasion_patterns:
  - "\\u200b"          # zero-width space (escape for YAML)
  - "---+"            # separadores exagerados
  - "__+"             # guiones bajos exagerados
  - "\\d{6,}"         # secuencia muy larga de dígitos
  - "http://"         # forzar http sin https

  # Indicadores genéricos de sospecha (phishing leve, ingeniería social suave)
  suspicious_markers:
    - "verifica ahora"
    - "confirma ahora"
    - "actualiza datos"
    - "restablecer acceso"
    - "seguridad de cuenta"
    - "actividad inusual"

  clean_senders_whitelist_domains:
    - "amazon.com"
    - "mercadolibre.com"
    - "mercadopago.com"
    - "banamex.com"
    - "bbva.com"
    - "santander.com.mx"
    - "hsbc.com.mx"
    - "microsoft.com"
    - "google.com"
    - "github.com"
    - "paypal.com"
    - "apple.com"
    - "outlook.com"
    - "gmail.com"
    - "protonmail.com"
    - "yahoo.com"
    - "paypal.com.mx"

  min_body_chars_for_real_mail: 60    # muy cortos suelen ser automáticos
  min_subject_chars: 3                # menos de 3 casi siempre es ruido


"# Nombres de categorías válidas": null
categories: ["Spam", "Clean", "Unknown", "Suspicious", "Scam"]

"# Cuentas a procesar (usan variables del .env)": null
accounts:
  - name: "Gmail_cacp18"
    enabled: true
    provider: "gmail"
    user_env: "GMAIL1_USER"
    pass_env: "GMAIL1_PASS"
    imap_server: "imap.gmail.com"
    port: 993

  - name: "Hotmail_cacp18"
    enabled: false
    provider: "hotmail"
    user_env: "HOTMAIL_USER"
    pass_env: "HOTMAIL_PASS"
    imap_server: "outlook.office365.com"
    port: 993

  - name: "Gmail_dataqbs"
    enabled: true
    provider: "gmail"
    user_env: "GMAIL2_USER"
    pass_env: "GMAIL2_PASS"
    imap_server: "imap.gmail.com"
    port: 993

"# Convención de nombre {email}_{Category}_{Correlativo}_{REGION}.eml": null
naming:
  pattern: "{email}_{category}_{index}_{region}.eml"
  zero_pad_width: 0   # 0 o, por ejemplo, 4 => 0001, 0002, ...

"# Pre-check: profundidades y muestra": null
precheck:
  max_list_per_folder: 10   # muestra de conteo por carpeta
  log_headers_sample: false  # true para ver headers en precheck

"# Reporte": null
report:
  create_json: true
  create_txt: true
  filename_json: "validation_report.json"
  filename_txt: "validation_report.txt"

"# Detección de idioma (rechazar si no coincide)": null
language_validation:
  enabled: true
  accept_if_empty_body: true  # si está vacío, deja pasar y lo revisa humano
  threshold_percent_es: 0.55  # si el texto es mayormente 'es' (heurística simple)
