############################################################
# Clean and unified config.yaml (only 5 labels: Scam, Sus, Spam, Clean, Unknown)
############################################################
accounts:
  - name: Gmail_cacp18
    provider: gmail
    user_env: GMAIL1_USER
    pass_env: GMAIL1_PASS
    imap_server: imap.gmail.com
    port: 993
    enabled: false
  - name: Gmail_dataqbs
    provider: gmail
    user_env: GMAIL2_USER
    pass_env: GMAIL2_PASS
    imap_server: imap.gmail.com
    port: 993
    enabled: false
  - name: Hotmail_main
    provider: hotmail
    user_env: HOTMAIL_USER
    pass_env: HOTMAIL_PASS
    imap_server: imap-mail.outlook.com
    port: 993
    enabled: true

max_age_days: 365
purge_saved_older_than_days: 365
exclude_thread_prefixes: ["re:", "fw:", "fwd:", "rv:", "res:"]
purge_thread_chains: true

language_validation:
  enabled: true
  threshold_percent_es: 0.70
  accept_if_empty_body: false

folders:
  gmail:
    include: ["INBOX", "[Gmail]/Spam"]
  hotmail:
    include: ["INBOX", "Junk Email", "Junk", "Junk E-mail", "Spam"]

transactional_short_allowlist:
  min_subject_chars: 3
  max_body_chars: 220
  trusted_domains:
    - bbva.mx
    - email.bbva.mx
    - bbva.com.mx
    - cfe.mx
    - citibanamex.com
    - scotiabank.mx
    - santander.com.mx
    - banorte.com
    - banamex.com
    - visa.com
    - mastercard.com
    - paypal.com
    - paypal.com.mx
    - booking.com
    - notice.aliexpress.com
    - 99minutos.com
    - boletomovil.com
    - opinioncinepolis.com
    - servicioscinepolis.com.mx
    - tripadvisor.com
    - accountprotection.microsoft.com
    - accounts.nintendo.com
    - google.com
    - instagram.com
    - x.com
    - apple.com
    - stripe.com
    - correo.profuturo.mx
    - support.facebook.com
  subject_must_match_one:
    - "código"
    - "token"
    - "verificación"
    - "confirmación"
    - "tu compra"
    - "pedido"
    - "entregado"
    - "en tránsito"
    - "comprobante"
    - "aviso"
    - "aviso de factura"
    - "estado de cuenta"
    - "recibo"
    - "receipt"
    - "comprobante de pago"
    - "recuperación de contraseña"
    - "restablecimiento de contraseña"

clean_marketing_rules:
  reputable_domains:
    - "mailchi.mp"
    - "hubspotlinks"
    - "beehiiv"
    - "adobe.com"
    - "netflix.com"
    - "spotify.com"
    - "amazon.com"
    - "openstageit.com"
  subject_markers:
    - "newsletter"
    - "boletín"
    - "novedades"
    - "actualizaciones"
    - "resumen semanal"
  max_links_ratio: 0.25

classifier:
  scoring:
    spam_keyword: 3
    scam_keyword: 4
    gambling_term: 2
    url_shortener: 3
    suspicious_header: 2
    suspicious_marker: 1
    evasion_pattern: 2
    suspicious_domain: 3
    frequent_spam_domain: 3
    urgency_pattern: 1
    phone_pattern: 2
    reputable_domain_clean_bonus: -1
    transactional_allow_bonus: -3
  thresholds:
    to_scam: 8
    to_sus: 4
    to_spam: 2
  hard_rules:
    scam_if:
      - any:
          - "scam_keywords>=2 AND url_shorteners>=1"
          - "urgency_patterns>=1 AND suspicious_headers>=1"
          - "evasion_patterns>=1 AND url_shorteners>=1"
          - "phone_patterns>=1 AND scam_keywords>=1"
    spam_if:
      - any:
          - "gambling_terms>=1"
          - "frequent_spam_domains>=1 AND url_shorteners>=1"
    clean_if:
      - any:
          - "newsletter>=1"
          - "transactional_short_allowlist matched"
          - "political_keywords>=1"
          - "fedex_shortener_combo>=1"

deduplication:
  enabled: true
  subject_fuzzy_ratio: 0.90
  body_min_chars_for_simhash: 120
  window_days: 365

min_body_chars_for_real_mail: 20
min_subject_chars: 3

report:
  create_json: true
  filename_json: validation_report.json
  create_txt: true
  filename_txt: validation_report.txt

output_path: emails_out
fetch:
  parallel_accounts: 5
  chunk_size: 200
naming:
  pattern: "{email}_{category}_{index}_{region}.eml"
  zero_pad_width: 4
output_structure:
  domain_subfolders: false  # save only by category, no subfolders by domain
language:
  code: es
  region_tag: ES

# Declarative domain classification used as tie-breakers
domain_classification:
  # Clearly legitimate domains (Clean)
  clean:
    - accounts.google.com
    - account.meta.com
    - accountprotection.microsoft.com
    - account.seeking.com
    - aexp.com
    - airbnb.com
    - amazon.com
    - amazon.com.mx
    - andela.com
  # aptino.com (clasificado como Sus/Unknown más abajo; removido de clean para coherencia)
    - arajet.zendesk.com
    - ascendion.com
    - asdeporte.com
    - ashbyhq.com
    - a.mercadolibre.com.mx
    - a.mercadopago.com
    - banamex.com
    - banregio.com
    - bbva.com
    - bbva.mx
    - beneficioscinepolis.com
    - bitso.com
    - boletia.com
    - boletomovil.com
    - boletomovil.info
    - booking.com
    - bybit.com
    - capgemini.com
    - certn.co
    - channels.primevideo.com
    - checkout.mastercard.com
    - chubb.com
    - citibanamex.com
    - coderbyte.com
    - comunicaciones.doters.com
    - connect.krispykreme.com.mx
    - conecta.hey.inc
    - contacto.volkswagen.mx
    - crossborderxpress.com
    - data.cloudera.com
    - dataqbs.com
    - deals.aliexpress.com
    - deel.support
    - docusign.net
    - doctoralia.com
    - dbtlabs.com
    - e.pearson.com
    - e.royaltonresorts.com
    - e-solutionsinc.com
    - email.bbva.mx
    - email.meetup.com
    - email.microsoft.com
    - email.storytel.com
    - email.clicktopay.visa.com
    - emailbanamex.com
    - emails.ticketmaster.com.mx
    - epam.com
    - express.medallia.com
    - facturadorelectronico.com
    - fans.formula1.com
    - f1lasvegasgp.com
    - gbm.com
    - gbm.com.mx
    - georgiait.com
    - getdbt.com
    - github.com
    - glassdoor.com
    - globalapplications.com
    - gobravo.mx
    - google.com
    - googlemail.com
    - hackerrankforwork.com
    - hcl.com
    - hcltech.com
    - heybanco.com
    - hola.banregio.com
    - hola.hey.inc
    - hotmail.com
    - idukay.com
    - imss.gob.mx
    - inmuebles24.com
    - insightglobal.com
    - info.epson.com
    - info.ticketmaster.com.mx
    - infoemails.microsoft.com
    - itransition.com
    - joinbairesdev.com
    - jm.indeed.com
    - leetcode.com
    - linkedin.com
    - lollapalooza.com
    - mail.formula1.com
    - mail.gobravo.mx
    - mail.innovasport.com
    - mail.meetup.com # alias
    - mailout.plex.tv
    - marketing.descript.com
    - match.indeed.com
    - mc.ihg.com
    - mercadolibre.com
    - mercadopago.com
    - microsoft.com
    - microsoftonline.com
    - microsoftstore.microsoft.com
    - mural.com.mx
    - mx.aeromexico.com
    - mx.aeromexicorewards.com
    - mx.didiglobal.com
    - mx.bitcar.mx
    - my.theladders.com
    - nrfm.com.mx
    - notifications.vivaaerobus.com
    - occ.mx
    - onedrive.com
    - openstageit.com
    - opinioncinepolis.com
    - outlier.ai
    - paypal.com.mx
    - payoneer.com
    - perficient.com
    - pitchparkevents.com
    - profuturo.com.mx
    - proxyvote.com
    - quadranttechnologies.com
    - reforma.com
    - reply.snowflake.com
    - r.mercadopago.com
    - samsung-mail.com
    - sat.gob.mx
    - scotiabank.mx
    - service.storytel.com
    - servicioscinepolis.com.mx
    - servicios.sorteostec.mx
    - sivale.com.mx
    - snowflake.com
    - snowflake.net
    - softtek.net
    - sonata-software.com
    - streamingbilling.disney.com
    - stripe.com
    - successfactors.com
    - successfactors.eu
    - techmahindra.com
    - televia.mx
    - tipmexico.com
    - tm.openai.com
    - tredence.com
    - trx.mail2.disneyplus.com
    - tsa.dhs.gov
    - tuexperiencia.citibanamex.com
    - tx.occmundial.com.mx
    - uber.com
    - us.fieldglass.cloud.sap
    - us.greenhouse-mail.io
    - uala.mx
    - vbeyond.com
    - verify.payoneer.com
    - vivaaerobus.com
    - welcome.americanexpress.com
    - whotels.com
    - nvio.mx
    - somoswim.com
    - indux.com
    - notification-2.bybit.com
    - send001.mail.bitget.com
    - send011.mail.bitget.com

  # Clean / Sus (marketing or variable content)
  clean_or_spam:
    - newsletter.vivaaerobus.com
    - comunicaciones.doters.com
    - promocinepolis.com
    - servicios.sorteostec.mx
    - email.flexjobs.com
    - noreply12.jobs2web.com
    - emails.roku.com
    - transak.com
    - x.com
    - updates.freelancer.com
    - vbeyond.com
    - aliexpress.com

  # Financial/e-commerce sensitive domains (potential phishing targets; keep watch)
  clean_or_scam_sensitive:
    - paypal.com.mx
    - amazon.com.mx
    - banamex.com
    - citibanamex.com
    - bbva.mx
    - payoneer.com
    - scotiabank.mx
    - stripe.com
    - mercadopago.com

  # Suspicious or lesser-known (Sus / Unknown)
  sus_or_unknown:
    - flap.com.mx
    - fastdolphin.com
    - pixie-services.com
    - republicachivas.fxp.mx
    - republicachivas.mx
    - tekleaders.com
    - aptino.com
    - ivedha.com
    - kryptosltd.co.uk
    - musicvibe.mx
    - ifit-solutions.com
    - welland.hk
    - astralcoach.com
    - blue.cloud
    - bluealtair.com
    - amaldate.com
    - amaze-systems.com
    - avanset.com
    - quantumworldit.com
    - redleosoft.com
    - yash.com
    - 4gds.net
    - 7-eleven.com.mx
    - 99minutos.com

  # Suspicious that may also end up as Spam (recurring patterns)
  sus_or_spam:
    - pegasotecnologiacfdi.mx
    - e.bitly.com


rules:
  url_shorteners:
    - "cutt.ly"
    - "bit.ly"
    - "shorturl.at"
    - "rebrand.ly"
    - "tinyurl.com"
    - "ow.ly"
    - "is.gd"
    - "t.co"
    - "lnkd.in"
  suspicious_headers:
    - "spf=fail"
    - "dkim=fail"
    - "dmarc=fail"
    - "Received-SPF: neutral"
    - "Received-SPF: softfail"
    - "authentication-results: fail"
  suspicious_markers:
    - "verifica ahora"
    - "confirma ahora"
    - "actualiza datos"
    - "restablecer acceso"
    - "seguridad de cuenta"
    - "actividad inusual"
    - "credenciales expiradas"
    - "tu suscripción ha expirado"
    - "renovar suscripción"
    - "ha sido bloqueada"
    - "necesita verificación"
  evasion_patterns:
    - "\\u200b"
    - "---+"
    - "__+"
    - "\\d{6,}"
    - "http://"
  urgency_patterns:
    - "urgente"
    - "atención inmediata"
    - "último aviso"
    - "última oportunidad"
    - "expira"
    - "vence hoy"
    - "no responda"
    - "accion requerida"
  political_keywords:
    - "ice"
    - "doge"
    - "trump"
    - "winred.com"
  phone_patterns:
    - "\\+52\\s?\\d{2,3}[\\s-]?\\d{3}[\\s-]?\\d{4}"
    - "\\b52\\d{10}\\b"
    - "\\b0?1?\\s?\\d{2,3}[\\s-]?\\d{3}[\\s-]?\\d{4}\\b"
  domain_overrides:
    force_clean_domains:
      - "dataqbs.com"
      - "mail.dataqbs.com"
      - "email.meetup.com"
      - "indeed.com"
      - "idukay.com"
      - "accounts.google.com"
      - "heybanco.com"
      - "nrfm.com.mx"
      - "insightglobal.com"
      - "match.indeed.com"
      - "tipmexico.com"
      - "mural.com.mx"
      - "reply.snowflake.com"
      - "redditmail.com"
      - "hggasesores.com"
      - "dbtlabs.com"
      - "onedrive.com"
      - "hexaware.com"
      - "mercadolibre.com"
      - "mnyl.com.mx"
      - "banregio.com"
      - "occ.mx"
      - "mx.didiglobal.com"
      - "servicios.sorteostec.mx"
    treat_fedex_shortener_as_clean: true
    force_spam_domains:
      - "citibanamex.com"
      - "mx.didiglobal.com"
      - "promocinepolis.com"
      - "email.storytel.com"
      - "asdeporte.com"
      - "account.pinterest.com"
      - "comunicaciones.doters.com"
  suspicious_domains:
    - "fzwmodel.com"
    - "mgjpanel.org"
    - "portierassociates"
    - "ctrk.klclick"
  credible_marketing_domains:
    - "amazon.com"
    - "mercadolibre.com"
    - "mercadopago.com"
    - "microsoft.com"
    - "google.com"
    - "netflix.com"
    - "spotify.com"
    - "adobe.com"
  scam_keywords:
    - "has ganado"
    - "ganaste"
    - "premio"
    - "bitcoin"
    - "suscripción ha expirado"
    - "renovar suscripción"
    - "factura"
    - "pago pendiente"
    - "verifica tu cuenta"
    - "credenciales expiradas"
    - "confirmar pago"
    - "hackeado"
  spam_keywords:
    - "oferta"
    - "promoción"
    - "descuento"
    - "marketing"
    - "gana dinero"
    - "trabajo desde casa"
    - "multinivel"
    - "promo"
    - "promocion"
    - "seguro de auto"
    - "aseguradora"
    - "garantizado"
    - "pierde *kg"
    - "pierde peso"
    - "baja de peso"
    - "aprovecha"
    - "no te lo pierdas"
    - "imperdible"
    - "última oportunidad"
    - "hoy solamente"
    - "vence hoy"
    - "envío gratis"
    - "sin costo"
    - "solo por hoy"
  gambling_terms:
    - "casino"
    - "apuesta"
    - "apuestas"
    - "freespins"
    - "spin"
    - "ruleta"
    - "jackpot"
  frequent_spam_domains:
    - "fzwmodel.com"
    - "mgjpanel.org"
    - "portierassociates"
    - "ctrk.klclick"
    - "destinycreditcard"
  # Duplicado temporal de umbrales (legacy fallback)
  min_body_chars_for_real_mail: 20
  min_subject_chars: 3

exclusions:
  blacklist:
    - pattern: "service@paypal.com.mx"
      subject_contains: ["receipt", "Receipt","Payment","payment","pago","comprobante","recibo"]
      reason: "personal_paypal_receipt"
    - pattern: "service@paypal.com"
      subject_contains: ["receipt","payment","pago","comprobante"]
      reason: "personal_paypal_receipt"
    - pattern: "member@paypal.com"
      subject_contains: ["receipt","payment","pago","comprobante"]
      reason: "personal_paypal_receipt"
    - pattern: "@paypal.com"
      subject_contains: ["receipt","payment","pago","comprobante","recibo","actividad de tu cuenta","alerta"]
      reason: "personal_paypal_general"
    - pattern: "families-noreply@google.com"
      subject_contains: ["nuevo"]
      reason: "personal_notification"
